Cambiar las unidades de esfuerzo a su forma inclusiva
IslasGECI/gatos pull request #4
Opened 2021-02-22 17:44 UTC by evaristor

2021-02-22 23:14 UTC, MaritzaB requested changes
Holi, aquí está mi revisión. Creo que una forma de llamar a _los tramperos_, que podría ayudarnos a mejorar es la de _personal de trampeo_.

2021-02-22 23:14 UTC, MaritzaB commented on python/templates/templates/esfuerzo-para-concluir-erradicacion.html
> +                        Se requieren {{ estado_gatos.dias_esfuerzo_trampas_mayor_95 | int }} días si se utilizan 10 personas, con 30 trampas cada uno.
```suggestion
                        Se requieren {{ estado_gatos.dias_esfuerzo_trampas_mayor_95 | int }} días si se utilizan 10 personas para trampeo, con 30 trampas cada uno.

```

2021-02-22 23:14 UTC, MaritzaB commented on python/templates/templates/esfuerzo-para-concluir-erradicacion.html
> +                        Si quisiéramos terminar la erradicación en 100 días, se requerirían {{ estado_gatos.personas_100_dias | int }} personas con 30 trampas cada uno.
```suggestion
                        Si quisiéramos terminar la erradicación en 100 días, se requerirían {{ estado_gatos.personas_100_dias | int }} personas para trampeo con 30 trampas cada uno.

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_diaria_isla_guadalupe.md
> +- Posible salida a punta sur para reunirnos con el grupo de personas. De realizarse el traslado no sé cuánto dure el viaje y la instalación en el campamento.
```suggestion
- Posible salida a punta sur para reunirnos con el personal de trampeo. De realizarse el traslado no sé cuánto dure el viaje y la instalación en el campamento.

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_diaria_isla_guadalupe.md
> +| fecha de revision | ID de la persona | ID de trampa | condicion | captura |
```suggestion
| fecha de revision | ID del personal | ID de trampa | condicion | captura |

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_diaria_isla_guadalupe.md
> +- De la discusión resultó que la nomenclatura del identificador de las trampas resultaba confuso, ya que se repetían series de números por persona, teniendo muchas trampas con numeración del 1-30 en
```suggestion
- De la discusión resultó que la nomenclatura del identificador de las trampas resultaba confuso, ya que se repetían series de números por persona, teniendo muchas trampas con numeración del 1-30 en el mismo sector (en este momento cada persona está trabajando con 30 trampas); llegamos a un acuerdo para disponer números consecutivos a las trampas por sector, quedando de la siguiente manera: `TT-XX-YYY-AA`, donde: TT es el tipo de trampa; `XX` es el sector que se está trabajando; `YYY` es el número de la trampa (que irá de 1-40 para la primer persona, del 41-80 para la segunda persona, del 81-120 para la tercera persona, y así sucesivamente); y `AA` son las iniciales del personal de trampeo.

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_diaria_isla_guadalupe.md
> +- Acompañé a todo el equipo de gatos al campo, incluyendo a las personas encargadas de las trampas,
```suggestion
- Acompañé a todo el equipo de gatos al campo, incluyendo al personal de trampeo,

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_semanal_isla_guadalupe.md
> +- Después de platicar un par de ocasiones con Luciana Luna sobre la tabla `POSICION_TRAMPAS_CEPO.XLSX`, terminamos con un diseño que les ayudará a las personas a tener cierto control sobre la informa
```suggestion
- Después de platicar un par de ocasiones con Luciana Luna sobre la tabla `POSICION_TRAMPAS_CEPO.XLSX`, terminamos con un diseño que les ayudará al personal a tener cierto control sobre la información diaria de las trampas y nos permitirá a nosotros hacer el procesamiento. 

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_semanal_isla_guadalupe.md
> +- Trabajaré con David Nájera y Carlos Tafoya para acordar el seguimiento de la actualización de los datos dentro de los archivos. David Nájera se quedará a cargo del equipo de personas y acordaré con
```suggestion
- Trabajaré con David Nájera y Carlos Tafoya para acordar el seguimiento de la actualización de los datos dentro de los archivos. David Nájera se quedará a cargo del personal de trampeo y acordaré con él delegar a Carlos Tafoya la función de actualizar las tablas de datos.

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_semanal_isla_guadalupe.md
> +- Trabajaré junto con David Cosío, David Nájera y algunas personas más en una práctica para la toma de datos de los transectos nocturnos para avistamiento de gatos.
```suggestion
- Trabajaré junto con David Cosío, David Nájera y algunas personas de trampeo más en una práctica para la toma de datos de los transectos nocturnos para avistamiento de gatos.

```

2021-02-22 23:14 UTC, MaritzaB commented on referencias/bitacora_semanal_isla_guadalupe.md
> +| fecha de revision | ID de la persona | ID de trampa | condicion | captura |
```suggestion
| fecha de revision | Iniciales del personal | ID de trampa | condicion | captura |

```

2021-02-22 23:37 UTC, evaristor commented
@MaritzaB Muchas gracias por tu revisión. Me gusta la sugerencia de usa _personal de trampeo_ en lugar de _tramperos_. Acepté tus amables sugerencias y agregué un par de cambios nuevos ("cada uno" por "cada persona") que se me habian escapado

2021-02-23 23:39 UTC, MaritzaB approved these changes
Creo que se ve bien. Muchas gracias @evaristor ✌🏽 .

2021-02-23 23:55 UTC, evaristor commented
Gracias a ti @MaritzaB

2021-02-23 23:56 UTC, merged