Migrate gatos to pymc3
IslasGECI/gatos pull request #6
Opened 2021-05-05 20:19 UTC by islasfernando

2021-05-07 20:57 UTC, nepito requested changes
Aquí te dejo dos comentarios para que podamos pasar el `make check`

2021-05-07 20:57 UTC, nepito commented on gatos/PopulationEstimator.py
>  def _find_quartil_hpd(archivo: str, porcentaje_datos_excluidos: float = 0.95):
Antes cargábamos `hpd` de `from pymc.utils import hpd ` pero ahora ya no lo hacemos. Por favor agrega cómo lo cargamos para que pasemos el `make check`.

2021-05-07 20:57 UTC, nepito commented on gatos/PopulationEstimator.py
> +            captures_obs = pm3.Binomial(
El `check make` nos dice que no utilizamos la variable `captures_obs` ¿será cierto o tendremos que agregar un `#  noqa` porque no sabe cómo identificarlo?

2021-06-22 22:01 UTC, nepito requested changes
Aquí te dejo mi revisión

2021-06-22 22:01 UTC, nepito commented on setup.py
> +        "pymc3",
Será posible quitar `numpy` y `pandas` del Dockerfile y agregarlos aquí:
```suggestion
        "numpy",
        "pandas",
        "pymc3",    
```

2021-06-22 22:01 UTC, nepito commented on Dockerfile
> +    pandas \
Será posible borrar estas dependencias y ponerlas en el setup.py

2021-06-22 22:01 UTC, nepito commented on Dockerfile
> +    pymc3 \
¿Será posible borrar esto de aquí y ponerlos en el setup.py?

2021-06-22 22:01 UTC, nepito commented on gatos/PopulationEstimator.py
> +        results_df = pd.DataFrame({"a": [], "b": [], "No": []})
Parece que ya no utilizas esta variable. ¿La podemos borrar?
```suggestion
```

2021-06-23 15:21 UTC, islasfernando commented on gatos/PopulationEstimator.py
>  def _find_quartil_hpd(archivo: str, porcentaje_datos_excluidos: float = 0.95):
Ya agrege uno que se llama igual, pero no se si hace exactamente lo mismo

2021-06-23 15:25 UTC, islasfernando commented on gatos/PopulationEstimator.py
> +            captures_obs = pm3.Binomial(
Si se ocupa. Nomás no se llama en otro lugar. Le puse el #noqa

2021-06-23 15:34 UTC, islasfernando commented on gatos/PopulationEstimator.py
>  def _find_quartil_hpd(archivo: str, porcentaje_datos_excluidos: float = 0.95):
Está [hdi](https://arviz-devs.github.io/arviz/api/generated/arviz.hdi.html#arviz.hdi), no hdp..

2021-06-29 21:18 UTC, merged